name: my_ai_pal
description: "Flutter AI Companion App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  http: ^1.2.1
  flutter_secure_storage: ^9.2.2
  connectivity_plus: ^7.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  provider: ^6.1.2
  crypto: ^3.0.3
  flutter_dotenv: ^6.0.0
  intl: ^0.20.2
  flutter_bloc: ^9.1.1
  animated_gradient: ^0.0.1
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  
  assets:
    - .env
